Repository infrawatch/service-telemetry-operator, pull requests merged in 2020-12, with the labels that each got.

#154 Fix typo in parameter name
  tests/infrared/16/stf-gnocchi-connectors.yaml.template
Labels: bug

#156 Drop PREFIX and bump OSP13 test scripts to latest puddle
  tests/infrared/13/infrared-openstack.sh
Labels: enhancement

#157 Make STF deployment optional in OSP13 test harness
  tests/infrared/13/infrared-openstack.sh
Labels: enhancement

#153 Use hostname -s to create unique cluster hostnames
  tests/infrared/16/infrared-openstack.sh
Labels: question
