Repository infrawatch/service-telemetry-operator, pull requests merged in 2020-01, with the labels that each got.

#28 Instantiate alertmanager
  README.md
  deploy/crds/infra.watch_serviceassurances_crd.yaml
  deploy/olm-catalog/service-assurance-operator/0.1.0/infra.watch_serviceassurances_crd.yaml
  deploy/olm-catalog/service-assurance-operator/0.1.0/service-assurance-operator.v0.1.0.clusterserviceversion.yaml
  roles/serviceassurance/defaults/main.yml
  roles/serviceassurance/tasks/component_alertmanager.yml
  roles/serviceassurance/tasks/sa_metrics.yml
Labels: enhancement

#31 [HOTFIX] Update invalid syntax for alertmanager manifest
  roles/serviceassurance/tasks/component_alertmanager.yml
Labels: bug

#27 Initial working implementation of ECK
  .gitignore
  build/Dockerfile
  build/push_app2quay.sh
  build/update_csv.sh
  deploy/olm-catalog/service-assurance-operator/0.1.1/infra.watch_serviceassurances_crd.yaml
  deploy/olm-catalog/service-assurance-operator/0.1.1/service-assurance-operator.v0.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/service-assurance-operator/service-assurance-operator.package.yaml
  deploy/role.yaml
  roles/serviceassurance/defaults/main.yml
  roles/serviceassurance/tasks/_local_signing_authority.yml
  roles/serviceassurance/tasks/_setup_certificates.yml
  roles/serviceassurance/tasks/component_certificates.yml
  roles/serviceassurance/tasks/component_elasticsearch.yml
  roles/serviceassurance/tasks/component_events_smartgateway.yml
  roles/serviceassurance/tasks/sa_events.yml
Labels: enhancement

#35 Add reference to alertmanager
  roles/serviceassurance/tasks/component_prometheus.yml
Labels: bug, enhancement
