Repository infrawatch/service-telemetry-operator, pull requests merged in 2020-04, with the labels that each got.

#83 Resolve issues with deploy_ci.sh script
  build/metadata.sh
  deploy/deploy_local_build.sh
Labels: bug

#82 Smart Gateway deployment improvements
  roles/servicetelemetry/tasks/base_smartgateway.yml
  roles/servicetelemetry/tasks/component_events_smartgateway.yml
  roles/servicetelemetry/tasks/component_metrics_smartgateway.yml
  roles/servicetelemetry/templates/manifest_smartgateway_events.j2
  roles/servicetelemetry/templates/manifest_smartgateway_metrics.j2
Labels: enhancement

#85 Set label so tuned executes for elasticsearch mmap
  roles/servicetelemetry/templates/manifest_elasticsearch.j2
Labels: bug, enhancement

#88 Update recommended memory defaults in crc-stf.sh
  tests/infrared/crc-stf.sh
Labels: enhancement

#87 Tweaks to result in an OSP16 deployment
  tests/infrared/16/infrared-openstack.sh
  tests/infrared/16/metrics-qdr-connectors.yaml.template
Labels: enhancement
