Repository infrawatch/service-telemetry-operator, pull requests merged in 2021-07, with the labels that each got.

#224 Deploy a sensubility smartgateway
  roles/servicetelemetry/defaults/main.yml
Labels: enhancement

#226 Adjust sensubility telemetry bus topic
  tests/infrared/16/stf-connectors.yaml.template
Labels: enhancement

#227 Adjust sensubility telemetry bus topic (#226)
  tests/infrared/16/stf-connectors.yaml.template
Labels: 1.3, cherry-pick

#228 Adjust bundle Dockerfile to build for a bundle
  deploy/olm-catalog/service-telemetry-operator/Dockerfile.in
Labels: 1.3, needs-backport

#230 Adjust bundle Dockerfile to build for a bundle (#228)
  deploy/olm-catalog/service-telemetry-operator/Dockerfile.in
Labels: 1.3, cherry-pick

#234 adjust elasticsearch timefield to exist with new event data model (#232)
  roles/servicetelemetry/templates/manifest_grafana_ds.j2
Labels: 1.3, cherry-pick

#231 Fix up multi-cloud scenarios to match documentation
  tests/infrared/13/enable-stf.yaml.template
  tests/infrared/13/infrared-openstack.sh
  tests/infrared/13/stf-connectors.yaml.template
  tests/infrared/16/enable-stf.yaml.template
  tests/infrared/16/infrared-openstack.sh
  tests/infrared/16/stf-connectors.yaml.template
Labels: 1.3, needs-backport, needs-testing

#235 Fix up multi-cloud scenarios to match documentation (#231)
  tests/infrared/13/enable-stf.yaml.template
  tests/infrared/13/infrared-openstack.sh
  tests/infrared/13/stf-connectors.yaml.template
  tests/infrared/16/enable-stf.yaml.template
  tests/infrared/16/infrared-openstack.sh
  tests/infrared/16/stf-connectors.yaml.template
Labels: 1.3, cherry-pick

#236 Enable Ceilometer events
  tests/infrared/16/enable-stf.yaml.template
Labels: 1.3, do-not-merge, needs-backport, needs-testing

#237 Enable Ceilometer events (#236)
  tests/infrared/16/enable-stf.yaml.template
Labels: 1.3, cherry-pick

#238 Fix syntax for fqdn_canonical hiera path
  tests/infrared/16/enable-stf.yaml.template
Labels: 1.3, cherry-pick
