Repository infrawatch/service-telemetry-operator, pull requests merged in 2022-11, with the labels that each got.

#383 Fixes for 17.0 ir script (#380)
  tests/infrared/17.0/infrared-openstack.sh
  tests/infrared/17.0/stf-connectors.yaml.template
Labels: cherry-pick, 1.5

#387 Make all certs 8yr expiry
  build/stf-run-ci/tasks/clone_repos.yml
  roles/servicetelemetry/defaults/main.yml
  roles/servicetelemetry/tasks/_local_signing_authority.yml
  roles/servicetelemetry/tasks/component_qdr.yml
  tests/smoketest/smoketest.sh
Labels: needs-backport, 1.5

#389 Make all certs 8yr expiry (#387)
  build/stf-run-ci/tasks/clone_repos.yml
  roles/servicetelemetry/defaults/main.yml
  roles/servicetelemetry/tasks/_local_signing_authority.yml
  roles/servicetelemetry/tasks/component_qdr.yml
  tests/smoketest/smoketest.sh
Labels: cherry-pick, 1.5

#391 Expand support for OCP 4.11
  build/stf-run-ci/tasks/setup_base.yml
  deploy/olm-catalog/service-telemetry-operator/Dockerfile.in
  deploy/olm-catalog/service-telemetry-operator/manifests/service-telemetry-operator.clusterserviceversion.yaml
  tests/smoketest/smoketest.sh
  tests/smoketest/smoketest_job.yaml.template
Labels: needs-backport, 1.5

#388 Force SGO checkout during build
  build/stf-run-ci/tasks/clone_repos.yml
Labels: needs-backport, 1.4, 1.5
