Repository infrawatch/service-telemetry-operator, pull requests merged in 2022-06, with the labels that each got.

#343 Adding a base_dir variable
  build/stf-run-ci/defaults/main.yml
  build/stf-run-ci/tasks/main.yml
  build/stf-run-ci/tasks/setup_stf_from_bundles.yml
  build/stf-run-ci/tasks/setup_stf_local_build.yml
Labels: needs-backport

#354 Replace "." for "-" in ci namespaces (#349)
  Jenkinsfile
Labels: cherry-pick, 1.4

#358 Sync the build/ directory from master
  build/stf-run-ci/README.md
  build/stf-run-ci/defaults/main.yml
  build/stf-run-ci/tasks/clone_repos.yml
  build/stf-run-ci/tasks/setup_stf_local_build.yml
Labels: 1.4

#355 Replace "." for "-" in ci namespaces (#349)
  Jenkinsfile
Labels: cherry-pick, 1.3

#359 Sync roles/ and deploy/ directory from master
  deploy/olm-catalog/service-telemetry-operator/manifests/service-telemetry-operator.clusterserviceversion.yaml
  deploy/role.yaml
  roles/servicetelemetry/tasks/main.yml
  roles/servicetelemetry/templates/manifest_loki.j2
Labels: 1.4

#360 Add logging to perftest-dashboard (#310)
  tests/performance-test/dashboards/perftest-dashboard.yaml
Labels: 1.4

#362 Rewrite Jenkinsfile to declarative syntax and skip CI on certain files (#356)
  Jenkinsfile
Labels: cherry-pick, 1.3
