Repository infrawatch/service-telemetry-operator, pull requests merged in 2023-11, with the labels that each got.

#520 Adjust QDR authentication password generation
  roles/servicetelemetry/tasks/component_qdr.yml
Labels: needs-testing

#518 Fix qdr auth one_time_upgrade label check
  roles/servicetelemetry/tasks/component_qdr.yml
Labels: needs-backport

#530 Restart QDR after changing the password
  ci/vars-zuul-common.yml
  roles/servicetelemetry/tasks/component_qdr.yml
  tests/smoketest/smoketest.sh
Labels: needs-backport

#534 Restart QDR after changing the password (#530)
  ci/vars-zuul-common.yml
  roles/servicetelemetry/tasks/component_qdr.yml
  tests/smoketest/smoketest.sh
Labels: cherry-pick

#535 Support OCP v4.12 through v4.14
  deploy/olm-catalog/service-telemetry-operator/Dockerfile.in
Labels: needs-backport

#536 Support OCP v4.12 through v4.14 (#535)
  deploy/olm-catalog/service-telemetry-operator/Dockerfile.in
Labels: cherry-pick

#538 Adjust Operator dependency version requirements
  deploy/olm-catalog/service-telemetry-operator/metadata/properties.yaml
Labels: needs-backport

#541 Only require Interconnect and Smart Gateway
  build/stf-run-ci/tasks/create_catalog.yml
  build/stf-run-ci/tasks/pre-clean.yml
  build/stf-run-ci/tasks/preflight_checks.yml
  build/stf-run-ci/tasks/setup_base.yml
  build/stf-run-ci/tasks/setup_stf.yml
  deploy/olm-catalog/service-telemetry-operator/metadata/properties.yaml
Labels: needs-backport

#543 Adjust Operator dependency version requirements (#538)
  build/stf-run-ci/tasks/create_catalog.yml
  build/stf-run-ci/tasks/pre-clean.yml
  build/stf-run-ci/tasks/preflight_checks.yml
  build/stf-run-ci/tasks/setup_base.yml
  build/stf-run-ci/tasks/setup_stf.yml
  deploy/olm-catalog/service-telemetry-operator/metadata/properties.yaml
Labels: cherry-pick
